# Generated by Django 4.1 on 2022-10-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LabourReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200, null=True)),
                ('ActivityName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.addlabour')),
            ],
        ),
        migrations.CreateModel(
            name='ProductivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('Deployment', models.IntegerField(default=1, null=True)),
                ('Length', models.IntegerField(default=1, null=True)),
                ('Breadth', models.IntegerField(default=1, null=True)),
                ('Depth', models.IntegerField(default=1, null=True)),
                ('Quantity', models.IntegerField(default=1, null=True)),
                ('ActivityName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.labourofcontractor')),
                ('ActivityNameBeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.addlabour')),
                ('Areaname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.area')),
                ('CategoryName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductivityReport.categoryofdeployment')),
                ('ContractorName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.contractordetail')),
                ('StructureName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure')),
            ],
        ),
        migrations.CreateModel(
            name='ProductivityNightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('Deployment', models.IntegerField(default=1, null=True)),
                ('Length', models.IntegerField(default=1, null=True)),
                ('Breadth', models.IntegerField(default=1, null=True)),
                ('Depth', models.IntegerField(default=1, null=True)),
                ('Quantity', models.IntegerField(default=1, null=True)),
                ('ActivityName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.labourofcontractor')),
                ('ActivityNameBeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.addlabour')),
                ('Areaname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.area')),
                ('CategoryName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductivityReport.categoryofdeployment')),
                ('ContractorName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.contractordetail')),
                ('StructureName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure')),
            ],
        ),
    ]
