# Generated by Django 4.1 on 2022-10-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0007_rename_deployment_siteengnight_nolabor'),
        ('ProductivityReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivityreport',
            name='ActivityName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActivityName', to='LabourReport.siteengday'),
        ),
        migrations.AlterField(
            model_name='productivityreport',
            name='ContractorName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.siteengday'),
        ),
    ]
