# Generated by Django 4.1 on 2022-10-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0008_categoryofdeployment'),
        ('ProductivityReport', '0002_alter_productivityreport_activityname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivityreport',
            name='ActivityNameBeta',
        ),
        migrations.AlterField(
            model_name='productivitynightreport',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.categoryofdeployment'),
        ),
        migrations.AlterField(
            model_name='productivityreport',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.categoryofdeployment'),
        ),
        migrations.DeleteModel(
            name='CategoryOfDeployment',
        ),
    ]
