# Generated by Django 4.1 on 2022-11-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0012_alter_area_username'),
        ('ProductivityReport', '0004_remove_productivitynightreport_activityname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivitynightreport',
            name='Areaname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.area'),
        ),
        migrations.AddField(
            model_name='productivitynightreport',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productivityreport',
            name='Areaname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.area'),
        ),
        migrations.AddField(
            model_name='productivityreport',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
