# Generated by Django 4.1 on 2022-11-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0012_alter_area_username'),
        ('ProductivityReport', '0005_productivitynightreport_areaname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityreport',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CatName', to='LabourReport.siteengday'),
        ),
        migrations.AddField(
            model_name='productivityreport',
            name='ContractorName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.siteengday'),
        ),
        migrations.AddField(
            model_name='productivityreport',
            name='LabourCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabourCat', to='LabourReport.siteengday'),
        ),
    ]
