# Generated by Django 4.1 on 2022-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductivityReport', '0006_productivityreport_categoryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivityreport',
            name='CategoryName',
        ),
        migrations.RemoveField(
            model_name='productivityreport',
            name='ContractorName',
        ),
        migrations.RemoveField(
            model_name='productivityreport',
            name='LabourCategory',
        ),
        migrations.AddField(
            model_name='productivityreport',
            name='LRid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
