# Generated by Django 4.1 on 2022-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductivityReport', '0009_alter_productivityreport_lrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityreport',
            name='Unit',
            field=models.CharField(choices=[('', 'None'), ('m', 'm'), ('m sq.', 'm sq.'), ('m cube', 'm cube')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productivityreport',
            name='Breadth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productivityreport',
            name='Depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productivityreport',
            name='Length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productivityreport',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
    ]
