# Generated by Django 4.1 on 2022-10-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteengday',
            name='StructureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure'),
        ),
    ]
