# Generated by Django 4.1 on 2022-10-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0002_siteengday_structurename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteengday',
            name='StructureName',
        ),
    ]
