# Generated by Django 4.1 on 2022-10-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0004_siteengday_structurename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteengday',
            old_name='NoLabor',
            new_name='Deployment',
        ),
        migrations.RenameField(
            model_name='siteengnight',
            old_name='NoLabor',
            new_name='Deployment',
        ),
    ]
