# Generated by Django 4.1 on 2022-10-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0005_rename_nolabor_siteengday_deployment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteengday',
            old_name='Deployment',
            new_name='NoLabor',
        ),
    ]
