# Generated by Django 4.1 on 2022-10-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0006_rename_deployment_siteengday_nolabor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteengnight',
            old_name='Deployment',
            new_name='NoLabor',
        ),
    ]
