# Generated by Django 4.1 on 2022-10-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0007_rename_deployment_siteengnight_nolabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200, null=True)),
                ('ActivityName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.addlabour')),
            ],
        ),
    ]
