# Generated by Django 4.1 on 2022-10-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0008_categoryofdeployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteengday',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.categoryofdeployment'),
        ),
        migrations.AddField(
            model_name='siteengnight',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.categoryofdeployment'),
        ),
    ]
