# Generated by Django 4.1 on 2022-11-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0009_siteengday_categoryname_siteengnight_categoryname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='cliday',
            name='NoHelp',
        ),
        migrations.RemoveField(
            model_name='clinight',
            name='NoHelp',
        ),
        migrations.RemoveField(
            model_name='sliday',
            name='NoHelp',
        ),
        migrations.RemoveField(
            model_name='slinight',
            name='NoHelp',
        ),
        migrations.AddField(
            model_name='cliday',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.categoryofdeployment'),
        ),
        migrations.AddField(
            model_name='cliday',
            name='StructureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure'),
        ),
        migrations.AddField(
            model_name='clinight',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.categoryofdeployment'),
        ),
        migrations.AddField(
            model_name='clinight',
            name='StructureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure'),
        ),
        migrations.AddField(
            model_name='sliday',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.categoryofdeployment'),
        ),
        migrations.AddField(
            model_name='sliday',
            name='StructureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure'),
        ),
        migrations.AddField(
            model_name='slinight',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.categoryofdeployment'),
        ),
        migrations.AddField(
            model_name='slinight',
            name='StructureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure'),
        ),
    ]
